from .base import Hаndler  # noqa
from .product import *  # noqa
from .article import *  # noqa
from .type_solution_create import TypeSolutionCreateHandler  # noqa
from .type_solution_get_all import TypeSolutionGetAllHandler  # noqa
from .type_object_create import TypeObjectCreateHandler  # noqa
from .type_object_get_all import TypeObjectGetAllHandler  # noqa
from .get_image import ImageGetHandler  # noqa
from .forwarding_feedback import ForwardingFeedbackHandler  # noqa
