version: '3.8'

services:
  db:
    container_name: ${PROJECT_NAME}_database
    image: postgres:14
    volumes:
      - ${PROJECT_NAME}_database_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure

  migrations:
    container_name: ${PROJECT_NAME}_migrations
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: ["make", "migrate-up"]
    depends_on:
      - db
    env_file:
      - .env

  backend: 
    container_name: ${PROJECT_NAME}_backend
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: ["make", "run-backend-uvi"]
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_PORT}
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_started
    restart: always
  
volumes:
 mirel_database_data: