"""empty message

Revision ID: 1bcfeeeafe7f
Revises: 3ade76d9f783
Create Date: 2023-06-05 13:24:38.799114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bcfeeeafe7f"
down_revision = "3ade76d9f783"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("products_description_key", "products", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "products_description_key", "products", ["description"]
    )
    # ### end Alembic commands ###
