"""empty message

Revision ID: 1d3f1461299f
Revises: da4e709109f8
Create Date: 2023-07-06 00:55:58.665810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d3f1461299f"
down_revision = "da4e709109f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_to_image_product",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("link", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_table(
        "product_link_to_image",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("link_to_image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["link_to_image_id"],
            ["link_to_image_product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
    )
    op.drop_constraint(
        "products_link_to_image_key", "products", type_="unique"
    )
    op.drop_column("products", "link_to_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "link_to_image",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        "products_link_to_image_key", "products", ["link_to_image"]
    )
    op.drop_table("product_link_to_image")
    op.drop_table("link_to_image_product")
    # ### end Alembic commands ###
