"""empty message

Revision ID: 32ee7ead7422
Revises: 8662225e788d
Create Date: 2023-06-15 18:08:43.560551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32ee7ead7422"
down_revision = "8662225e788d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "type_object", ["name"])
    op.create_unique_constraint(None, "type_solution", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "type_solution", type_="unique")
    op.drop_constraint(None, "type_object", type_="unique")
    # ### end Alembic commands ###
