"""empty message

Revision ID: 33aada8347ea
Revises: 
Create Date: 2023-06-04 21:02:20.943312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33aada8347ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("preview_description", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "link_to_preview_image", sa.String(length=100), nullable=False
        ),
        sa.Column("link_to_image", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("link_to_image"),
        sa.UniqueConstraint("link_to_preview_image"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("company", sa.String(length=40), nullable=False),
        sa.Column("type_solution", sa.String(length=50), nullable=False),
        sa.Column("type_object", sa.String(length=50), nullable=False),
        sa.Column("year_implementation", sa.Integer(), nullable=False),
        sa.Column("preview_description", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "link_to_preview_image", sa.String(length=100), nullable=False
        ),
        sa.Column("link_to_image", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("link_to_image"),
        sa.UniqueConstraint("link_to_preview_image"),
        sa.UniqueConstraint("type_object"),
        sa.UniqueConstraint("type_solution"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("articles")
    # ### end Alembic commands ###
