"""empty message

Revision ID: 3ade76d9f783
Revises: 33aada8347ea
Create Date: 2023-06-05 12:49:46.507976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ade76d9f783"
down_revision = "33aada8347ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "type_object",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "type_solution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "products", sa.Column("type_solution_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "products", sa.Column("type_object_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("products_type_object_key", "products", type_="unique")
    op.drop_constraint(
        "products_type_solution_key", "products", type_="unique"
    )
    op.create_foreign_key(
        None, "products", "type_solution", ["type_solution_id"], ["id"]
    )
    op.create_foreign_key(
        None, "products", "type_object", ["type_object_id"], ["id"]
    )
    op.drop_column("products", "type_solution")
    op.drop_column("products", "type_object")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "type_object",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "type_solution",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_unique_constraint(
        "products_type_solution_key", "products", ["type_solution"]
    )
    op.create_unique_constraint(
        "products_type_object_key", "products", ["type_object"]
    )
    op.drop_column("products", "type_object_id")
    op.drop_column("products", "type_solution_id")
    op.drop_table("type_solution")
    op.drop_table("type_object")
    # ### end Alembic commands ###
