"""empty message

Revision ID: 7a567d09c615
Revises: bd52761d40e0
Create Date: 2023-07-06 12:05:44.391202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a567d09c615"
down_revision = "bd52761d40e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_description",
        sa.Column("product_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "product_description", "products", ["product_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_description", type_="foreignkey")
    op.drop_column("product_description", "product_id")
    # ### end Alembic commands ###
