"""empty message

Revision ID: bd52761d40e0
Revises: 1d3f1461299f
Create Date: 2023-07-06 11:54:57.434349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd52761d40e0"
down_revision = "1d3f1461299f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_description",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("line", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("line"),
    )
    op.drop_column("products", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_table("product_description")
    # ### end Alembic commands ###
