"""empty message

Revision ID: da4e709109f8
Revises: 32ee7ead7422
Create Date: 2023-07-05 19:26:46.463477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da4e709109f8"
down_revision = "32ee7ead7422"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "product_company",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
    )
    op.create_table(
        "product_type_object",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("type_object_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_object_id"],
            ["type_object.id"],
        ),
    )
    op.create_table(
        "product_type_solution",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("type_solution_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_solution_id"],
            ["type_solution.id"],
        ),
    )
    op.drop_constraint(
        "products_type_solution_id_fkey", "products", type_="foreignkey"
    )
    op.drop_constraint(
        "products_type_object_id_fkey", "products", type_="foreignkey"
    )
    op.drop_column("products", "company")
    op.drop_column("products", "type_solution_id")
    op.drop_column("products", "type_object_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "type_object_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "type_solution_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "company",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "products_type_object_id_fkey",
        "products",
        "type_object",
        ["type_object_id"],
        ["id"],
    )
    op.create_foreign_key(
        "products_type_solution_id_fkey",
        "products",
        "type_solution",
        ["type_solution_id"],
        ["id"],
    )
    op.drop_table("product_type_solution")
    op.drop_table("product_type_object")
    op.drop_table("product_company")
    op.drop_table("company")
    # ### end Alembic commands ###
