"""empty message

Revision ID: f9397e52de9c
Revises: 1bcfeeeafe7f
Create Date: 2023-06-05 18:02:54.487374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9397e52de9c"
down_revision = "1bcfeeeafe7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "link_to_preview_image", type_=sa.String(1000))
    op.alter_column("products", "link_to_image", type_=sa.String(1000))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "link_to_preview_image", type_=sa.String(100))
    op.alter_column("products", "link_to_image", type_=sa.String(100))
    # ### end Alembic commands ###
